### ISSUE TITLE
User can start their car

### ISSUE THREAD

**Issue by BenGrimmius** [BenGrimmius/driving-game#3]
## 💰 Motivation

It's a driving game, duh!

## 📐 Plan

Move the car a few pixels every 16 milliseconds when the user presses space.

## ✅ Task List

- [x] ... Create a simple data model that includes which way the car is facing, (north, south, east, or west).
- [x] ... Listen for keydown events for the space bar.
- [ ] ... Add code in the event listener that projects the car forward.
